### ISSUE TITLE
[feature/auth] 사용자 인증 기능 구현

### ISSUE THREAD

**Issue by 2yuna13** [2yuna13/2024-newsfeed#1]
## 📌Feature Issue
- 회원가입
- 로그인

## ✏️ To-do

1. 회원가입
- [x] username은  최소 4자 이상, 10자 이하이며 알파벳 소문자(a-z), 숫자(0-9)로 구성
- [x] password는  최소 8자 이상, 15자 이하이며 알파벳 대소문자(a-z, A-Z), 숫자(0~9), 특수문자로 구성
- [x] DB에 중복된 username과 email이 없다면 회원을 저장

2. 로그인
- [x] email, password를 Client에서 전달받기
- [x] DB에서 email을 사용하여 저장된 회원의 유무를 확인하고 있다면 password 비교
